name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  build:
    name: Lint and Typecheck
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node_version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node_version}}
        uses: actions/setup-node@v2
        with:
          node_version: ${{matrix.node_version}}

      - name: install npm dependencies
        run: |
          npm install

      - name: run typechek
        run: |
          npm run typecheck

      - name: run lint
        run: |
          npm run lint
